## numpy
科学计算库,提供了大量科学计算功能,底层为C,核心为多维数组类型,支持大量维度计算与矩阵运算,支持对ndarray对象的处理

In [ ]:
from numpy import dtype
import numpy as np
a = np.arange(10)#创建一个数组,arange([start,] stop[, step,], dtype=None, *, like=None): # real signature unknown; NOTE: unreliably restored from __doc__
b= np.arange(4,21,2,dtype=float)#创建4到20步长为2的数组

print(a)
print(type(a))

print(b)
print(type(b))

In [ ]:
import numpy as np
import math
b=[3,4,9]
for i in b:
    print(math.sqrt(i))#常规开平方

print(np.sqrt(b))#np开平方

In [ ]:
import numpy as np
#使用array创建一维数组
a=np.array([1,2,3,4,5])
#创建二维数组
b=np.array([[1,2,3],[4,5,6]])

print(a,type(a))
print(b,type(b))
#以此类推,不再列举
#dtype指定数组类型,ndmin指定数组的维度
b=np.array([[1,2,3],[4,5,6]],dtype=float,ndmin=2)
print('\n',b)

## 随机数组

In [ ]:
import numpy as np
#使用random创建,random创建0到1间数组,randint创建整数
a=np.random.random(size=5)#一维长度为5的0到1间的小数(左开右闭)
b=np.random.random(size=(3,4))#二维3行4列
c=np.random.random(size=(2,3,4))#二维3行4列

d=np.random.randint(2,18,size=(2,4),dtype=np.int64)#2行4列,2到18整数类型为int64,括号内参数可看情况删除

print(a,type(a),'\n')
print(b,type(b))
print(d,type(d))

In [ ]:
#正态分布randn
import numpy as np
#使用random创建,random创建0到1间数组,randint创建整数
a=np.random.randn(5)#一维长度为5,满足标准正态分布
b=np.random.randn(3,4)#二维3行4列
cc =np.random.randn(2,3,4)#三维两个3行4列
d=np.random.normal(size=5)#默认期望loc=0.0 ,方差为scale=1.0
e=np.random.normal(loc=2,scale=3,size=5)#默认期望loc=2 ,方差为scale=3
print(a,type(a))
print(b,type(b))
print(d,type(d))

### ndarray对象
Numpy最重要的一个特点是其N维数组对象 ndarray,它是一系列同类型数据的集
合，以0下标为开始进行集合中元素的索引。
ndarray对象是用于存放同类型元素的多维数组
ndarray中的每个元素在内存中都有相同存储大小的区域。
ndarray内部由以下内容组成
- 一个指向数据（内存或内存映射文件中的一块数据）的指针。
- 数据类型或 dtype,描述在数组中的固定大小值的格子。
- 一个表示数组形状( shape)的元组，表示各维度大小的元组。

Numpy的数组中比较重要 ndarray对象属性有：

|属性|说明|
|:---|:----|
|ndarray.ndim|秩，即轴的数量或维度的数量|
|ndarray.shape|数组的维度，对于矩阵，n行m列
ndarry.size|数组元素的总个数，相当于.shape中n*m的值
ndarray.dtype|ndarry对象的元素类型
ndarrav.itemsize|ndarry对象中每个元素的大小，以字节为单位
ndarray.flags|ndarray对象的内存信息
ndarray.real|ndarray元素的实部
ndarrav.imag|ndarray元素的虚部,包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不用

In [10]:
import numpy as np
a=np.array([1,2,3,4])#一维数组
b=np.random.randint(4,10,size=(2,3))#二维数组
print('ndim : ',a.ndim,b.ndim)#数组维度
print('shape : ',a.shape,b.shape)#数组形状
print('dtipe :',a.dtype,b.dtype)#数组类型
print('size : ',a.size,b.size)#数组元素个数
print('itermsize : ',a.itemsize,b.itemsize)#每个元素所占的字节

ndim :  1 2
shape :  (4,) (2, 3)
dtipe : int32 int32
size :  4 6
itermsize :  4 4


### 其他方式创建数组

|参数|描述|
|:--:|:------|
start|序列的起始值为：base来* start
stop|序列的终止值为：base*stop。如果end@ point为tnue,该值包含于数列中
num|要生成的等步长的样本数量，默认为50
endpoint|该值为ture时，数列中中包含stop值，反之不包含，默认是 True
base|对数log的底数。
dtype|ndarray的数据类型
np.zeros(shape, dtype=None, order='C', *args, **kwargs):零填充创建<br>
np.ones(shape, dtype=None, order='C', *args, **kwargs):一填充创建<br>
np.empty(shape, dtype=None, order='C', *args, **kwargs):开辟指定形状的数组空间(有值,值为上次用过的值)<br>
np.linspace(始,末,个数):等差数列,linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0),endpoint是否要尾值,默认步长为50<br>
d=np.logspace():等比数列

#### 切片的使用 [行进行切片,列进行切片]

In [13]:
import numpy as np
a=np.zeros(2)#一维
b=np.zeros((2,3))#二维,其他同类不再多说
c=np.linspace(1,10,4)
print(c)
d=np.logspace(0,9,10,base=2)
print(d)

[ 1.  4.  7. 10.]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [15]:
# 数组的切片
import numpy as np
#创建一维数组
a=np.arange(10)
print(a)
#正索引访问  索引从0开始  长度-1
print('索引0处的元素：',a[0])
print('索引5处的元素：',a[5])

#负索引访问  倒数第一个的索引为-1
print('访问最后一个元素：',a[-1])
print('访问倒数第三个元素：',a[-3])

#切片正向索引操作  [start:stop:step]
print(a[:])  #从开始到结尾
print(a[3:]) #从索引3开始到结尾
print(a[3:5]) #从索引3开始到索引4 [start,stop)结尾
print(a[1:7:2]) #从索引1开始到索引6，步长是2

#切片中负索引操作
print(a[::-1])  #反向获取
print(a[-5:-2])
#导入numpy模块
import numpy as np
#创建一维数组
a=np.arange(1,13)
print(a)
#对一维数组进行修改形状  (4,3)
a=a.reshape((4,3))
print(a)
#索引的使用
#获取第三行
print(a[2])
#获取第二行 第3列
print(a[1][2])

#切片的使用 [行进行切片,列进行切片]   [start:stop:step,start:stop:step]
#获取所有行所有列
print(a[:,:])
#获取所有行部分列   所有行第2列
print(a[:,1])
#获取所有行部分列   所有行第1,2列
print(a[:,0:2])

#获取部分行 所有列  获取奇数行所有列
print(a[::2,:])

#获取部分行 部分列   获取奇数行  第1,2列
print(a[::2,0:2])

#坐标获取 [行,列]
#获取第2行第3列的元素
print(a[1][2])
print(a[1,2])

#同时获取不同行不同列   获取第2行第3列  第3行第1列
print(a[1,2],a[2][0])
print(np.array([a[1,2],a[2][0]]))#将获取第2行第3列  第3行第1列合并为一个数组
#使用坐标
print(a[(1,2),(2,0)])

#负索引的使用
print('最后一行')
print(a[-1])
print('行倒序')
print(a[::-1])
print('行列倒序')
print(a[::-1,::-1])

[0 1 2 3 4 5 6 7 8 9]
索引0处的元素： 0
索引5处的元素： 5
访问最后一个元素： 9
访问倒数第三个元素： 7
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 4]
[1 3 5]
[9 8 7 6 5 4 3 2 1 0]
[5 6 7]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[7 8 9]
6
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 2  5  8 11]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[1 2 3]
 [7 8 9]]
[[1 2]
 [7 8]]
6
6
6 7
[6 7]
[6 7]
最后一行
[10 11 12]
行倒序
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]
行列倒序
[[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [7]:
#数组的复制
import numpy as np
a=np.arange(1,13).reshape((3,4))#改变数组维度,注意,3*4=12,拆分要满足元素个数这个潜在要求
print(a)
sub_a=a[:2,:2]
print(sub_a)
sub_a[0][0]=100
print('\n',a)#由此的切片获取的为浅拷贝,对浅拷贝得到的值修改会作用到原数组值上
sub_a=np.copy(a[:2,:2])
sub_a[0][0]=300
print('\n',a)#没影响原来数组的值

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]

 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


__维度的修改:__俩种方法如下例题<br>

除此之外,也可用resape,ravel,flatten转换为一维数组

    reshape(a, newshape, order='C'):
    """
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'},可选的,使用此索引顺序读取 `a` 的元素，并使用此索
        引顺序将元素放入重构的数组中。 'C' 表示使用类似 C 的索引顺序读写元素，最后一个轴索
        引变化最快，回到第一个轴索引变化最慢。 'F' 表示使用类似 Fortran 的索引顺序读写元素
        ，第一个索引变化最快，最后一个索引变化最慢。请注意，'C' 和 'F' 选项没有考虑底层数组
        的内存布局，只涉及索引的顺序。如果`a` 在内存中是Fortran 连续的，则'A' 表示以类似
        Fortran 的索引顺序读写元素，否则按照类似C 的顺序进行读写。

In [21]:
import numpy as np
aa=np.arange(16)
print(aa)
b=aa.reshape((2,8))
print(b)
b=np.reshape(aa,(4,4))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 数组的拼接

np.vstack(()):垂直拼接<br>
np.hstack(()):水平拼接<br>
np.concatenate(()):延轴拼接,几维有几个轴,默认axis为0,(请类比空间直角坐标系x0y1z2轴,0为纵向1为水平)

In [43]:
import  numpy as np

a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(3,4)[::-1]
print('a:\n',a,'\nb:\n',b)
r=np.vstack((a,b))
p=np.hstack((a,b))
print('r:\n',r,'\np:\n',p)
q=np.concatenate((a,b),axis=0)
print('q:\n',q)

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
b:
 [[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
r:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]] 
p:
 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  0  1  2  3]]
q:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


#### 数组的分割
 - split(ary, indices_or_sections, axis=0)<br>
     - 多维会延轴分割,几维有几个轴,默认axis为0,(请类比空间直角坐标系x0y1z2轴,0为纵向1为水平),
     - indices_or_sections为平均分割的份数,为数字时为平均分割,为[3]等列表时为按位置分割
 - hsplit:水平分割(h表示行)
 - vsplit:垂直分割

#### 数组转置
 transpose(a, axes=None)用法:
 1. a=数组.transpose()
 2. a=np.transpose(数组,维度)#维度这是一个元组

三维(i,j,k)转置默认为(k,j,i)

In [13]:
#一维
import numpy as np
a=np.arange(0,16)
a=np.split(a,4)
b=np.arange(0,16)
print(a)

c=[]
d=[]
c=[c.append(i) for i in b]#并没有传值进去
for i in b:
    d.append(i)
print(c)
print(d)

aa=np.reshape(b,(2,8))
a=aa.transpose()
print(a)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[[ 0  8]
 [ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]]


#### numpy函数

In [ ]:
#导入numpy
import numpy as np
a=np.arange(9).reshape(3,3)
b=np.array([10,10,10])
print('加法')
print(np.add(a,b))
print(a+b)
print('减法')
print(np.subtract(b,a))
print(b-a)

#out参数的使用
y=np.empty((3,3),dtype=np.int)
np.multiply(a,10,out=y)
print(y)

#三角函数
a=np.array([0,30,60,90])
print(np.sin(a))

#around ceil floor
a = np.array([1.0,4.55,  123,  0.567,  25.332])
print('around:',np.around(a))
print('ceil:',np.ceil(a))
print('floor:',np.floor(a))

#统计函数
# power()
a=np.arange(1,13).reshape(3,4)
print('原数组a')
print(a)
print('power:',np.power(a,2))

#power中out的使用
x=np.arange(5)
y=np.zeros(10)
np.power(2,x,out=y[:5])
print(y)

#  median ()
#一维数组的中位数
a=np.array([4,3,2,5,2,1]) #对数组排序 [1,2,2,3,4,5]  数组中元素个数为偶数 中位数指：中间两个数的平均值
print(np.median(a))

a=np.array([4,3,2,5,2]) #对数组排序 [2,2,3,4,5]  数组中元素个数为奇数 中位数指：中间的数
print(np.median(a))

#二维数组  要通过axis指定轴
a=np.arange(1,13).reshape(3,4)
print(a)
print('垂直方向 ',np.median(a,axis=0))
print('水平方向 ',np.median(a,axis=1))

#mean 求平均值
#一维数组
a=np.array([4,3,2,5,2])
print(np.mean(a))
#二维数组   axis指定轴求平均
a=np.arange(1,13).reshape(3,4)
print(a)
print('axis=0 垂直方向',np.mean(a,axis=0))
print('axis=1 水平方向',np.mean(a,axis=1))

#sum()  max()  min()
a=np.array([4,3,2,5,2])
print('max:',np.max(a))
print('sum:',np.sum(a))
print('min:',np.min(a))

#argmax argmin
print('argmin:',np.argmin(a))
print('argmax:',np.argmax(a))


